--INSERT INTO rail_line
INSERT INTO rail_line VALUES(1,100);
INSERT INTO rail_line VALUES(2,200);
INSERT INTO rail_line VALUES(3,150);
INSERT INTO rail_line VALUES(4,90);
INSERT INTO rail_line VALUES(5,500);
